homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_lat
  longitude: !secret location_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Allow diagnosing system problems
system_health:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: !secret server_port
  ssl_certificate: !secret https_ssl_cert
  ssl_key: !secret https_ssl_key

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include extraconfig/sensor.yaml
input_select: !include extraconfig/input_select.yaml
stream:
camera: !include extraconfig/camera.yaml

sonoff:
  username: bza.neo@gmail.com
  password: 3zyS6Hj9bUo67NR7EkKg

switch:
  - platform: broadlink
    mac: !secret broadlink_mini3_mac
    switches:
      - name: Horizon TV
        command_on: JgBIABkbPBsfGx4cHhsfODsbHzgeGzwbHwALmx4bPBseHB4bHxseODwbHjgfGzwbHgALnB0cOR4cHR0dHhwcOjodHDocHjkeHAANBQAAAAAAAAAAAAAAAAAA=
        command_off: JgBIABgdHR05HhwdHR0dOTodHTocHTodHQALnhwdHB45HR0dHR0cOjodHTkdHTodHAALnhseHB06HR0dHB4cOjodHDocHjkeHAANBQAAAAAAAAAAAAAAAAAA=
#device_tracker:
#- platform: snmp
#host: 192.168.24.1
#community: public
#baseoid: 1.3.6.1.2.1.4.22.1.2
#interval_seconds: 30
#consider_home: 120
