esphome:
  name: energy_power_plug_tuya
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: "IOT_IoT"
  password: !secret iot_iot_pass

  # Set this to the IP of the ESP
  manual_ip:
    static_ip: 192.168.50.103
    gateway: 192.168.50.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power Plug Tuya Fallback Hotspot"
    password: "kxU6GfEgXGsP"
# Enable logging
logger:
# Enable Web server
#web_server:
  #port: 80
# Enable Home Assistant API
api:
  password: !secret iot_iot_pass
ota:
  password: !secret iot_iot_pass
time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Power Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: Status

switch:
  - platform: gpio
    id: red_led
    name: "Tuya Red Led"
    pin:
      number: GPIO00
      #inverted: true
  - platform: gpio
    id: blue_led
    name: "Tuya Blue Led"
    pin:
      number: GPIO02
      #inverted: true

  - platform: gpio
    name: "Tuya Smart Plug"
    pin: GPIO15
    id: relay

    # Turn on red LED
    on_turn_on:
      - switch.turn_on: red_led

    # Turns off red LED
    on_turn_off:
      - switch.turn_off: red_led

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: 0.00265
    voltage_divider: 924
    current:
      name: "Tuya Smart Plug current"
      unit_of_measurement: A
    voltage:
      name: "Tuya Smart Plug Voltage"
      unit_of_measurement: V
    power:
      name: "Tuya Smart Plug Wattage"
      unit_of_measurement: W
      id: "energy_temp_Wattage"
    change_mode_every: 8
    update_interval: 10s